### ISSUE TITLE
CORS Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by lonelyteapot** [sharat87/httpbun#10]
Httpbun doesn't include [`Access-Control-Allow-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers) header in response to [`Access-Control-Request-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Request-Headers), which browsers populate for non-safelisted custom headers. This makes requests fail due to CORS.

Example:

![image](https://github.com/sharat87/httpbun/assets/50505104/844d7615-36c5-479b-9592-95f84f97798f)

This response should have contained `access-control-allow-headers: content-type` to succeed.

_Similar issue with httpbin: https://github.com/postmanlabs/httpbin/issues/147 (fixed)_

**Comment by sharat87** [comment]
Hey, thanks for including details of what this issue is, and links to references. Makes it much easier to move faster. This is fixed in https://github.com/sharat87/httpbun/commit/44326ef87df0ab398d3c3b584ecb21bdb7c95edb, and is live on httpbun.com.

![shot-2023-09-12-05-12-00](https://github.com/sharat87/httpbun/assets/120119/822eb25e-c326-4a99-aa74-1089b613fda5)

**Comment by lonelyteapot** [comment]
Wow, that was really fast, thanks!
