### ISSUE TITLE
`/headers` returns capitalized keys instead of original keys

### ISSUE THREAD

**Issue by AlexV525** [sharat87/httpbun#11]
Keys of headers should return as-is.

```console
$ curl -H 'Sensitive: test' -H 'insensitive: test' https://httpbun.com/headers
{
  "Accept": "*/*",
  "Connection": "close",
  "Host": "httpbun.com",
  "Insensitive": "test",
  "Sensitive": "test",
  "User-Agent": "curl/8.2.1"
}
```

Could be affected by
https://github.com/sharat87/httpbun/blob/44326ef87df0ab398d3c3b584ecb21bdb7c95edb/bun/headers/handler.go#L25
or
https://github.com/sharat87/httpbun/blob/44326ef87df0ab398d3c3b584ecb21bdb7c95edb/bun/headers/handler.go#L27

**Comment by sharat87** [comment]
Hey @AlexV525, thank you for raising this. This is indeed affecting me as well and I was looking into it a couple months back. I’ll pick it up again and see if we can figure it out.

I’m a little unavailable the next three weeks, so that’s the earliest I can pick this up unfortunately.

Thank you.

**Comment by AlexV525** [comment]
So far I can tell this is as intended in the Go source:
```go
// HTTP defines that header names are case-insensitive. The
// request parser implements this by using CanonicalHeaderKey,
// making the first character and any characters following a
// hyphen uppercase and the rest lowercase.
```
https://github.com/golang/go/blob/b5f87b5407916c4049a3158cc944cebfd7a883a9/src/net/http/request.go#L161-L164

**Comment by sharat87** [comment]
That’s right. That’s where I hit a block the last time I tried to solve this. I’d still want to be able to show the headers exactly as is. Let me try this again.

**Comment by AlexV525** [comment]
The simplest patch is to comment the line out: https://github.com/golang/go/blob/b5f87b5407916c4049a3158cc944cebfd7a883a9/src/net/textproto/reader.go#L528

**Comment by AlexV525** [comment]
Patch:
```shell
sed 's/\(key, ok :=\) canonicalMIMEHeaderKey(k)/key, ok := string(k), true/' "$(go env GOROOT)/src/net/textproto/reader.go" > x
```

Unpatch:
```shell
sed 's/\(key, ok :=\) string(k), true/key, ok := canonicalMIMEHeaderKey(k)/' "$(go env GOROOT)/src/net/textproto/reader.go" > x
```

**Comment by AlexV525** [comment]
It throws 400 after patches however...

**Comment by AlexV525** [comment]
Managed to apply patches and resolve the issue. See #12.

**Comment by sharat87** [comment]
Hey @AlexV525, thanks for spending time on this. I'm a little split on whether we should do this in the endpoints we already have, or introduce new ones, like `/get-raw`, `/headers-raw` etc. Because if header key canonicalization is disabled, we may see responses like:

```json
{
  "X-One": "first value",
  "x-one": "second value"
}
```

This looks fine when there's just 2-3 headers, but can be confusing and hard to glance over, like it is today. What we have today is _effective headers_, as opposed to _raw headers_ in the request. So I'm wondering if there's value in being able to see either of them, by preference, so `/headers` vs `/headers-raw`.

What do you think? Would that help?

**Comment by AlexV525** [comment]
That would a little bit complex to the current foundation. We'll need to invent more patches based on the entrypoint, and I'm not sure if it's possible to.

**Comment by AlexV525** [comment]
What we used to do is create a case-insensitive hashmap so it treats `X-One` and `x-one` as the same but keeping the first of it without modification.

**Comment by sharat87** [comment]
I see. Thanks. Although it looks like all httpbin.org, postman-echo.org, pie.dev and httpbingo.org respond with uniform casing, irrespective of what the request had. I'm currently inclined to keep it this way. This will make the responses be predictable, and since header keys are not case-sensitive, I'd say let's keep it this way.

**Comment by AlexV525** [comment]
Well I guess we need to implement our service for our tests then. Thanks anyway!
