### ISSUE TITLE
Add content length header to appropriate endpoints

### ISSUE THREAD

**Issue by kuhnroyal** [sharat87/httpbun#13]
I think `/payload` and `/get` responses should contain a `content-length` response header.
Maybe some others as well.

**Comment by sharat87** [comment]
Hey @kuhnroyal, thanks for reaching out. I do see the `Content-Length` header in the response from `/get`... am I missing something here? 🤔

![shot-2023-11-14-17-04-12](https://github.com/sharat87/httpbun/assets/120119/d232ceea-d556-43ed-9152-045ca5930ee0)

**Comment by kuhnroyal** [comment]
Hmm yes, I am confused. Could have sworn it wasn't there.
My bad.

**Comment by kuhnroyal** [comment]
Ah found it, when I `POST` a simple file to `/payload`, the response is missing the header.

**Comment by kuhnroyal** [comment]
Also `/bytes` could have the header.

**Comment by sharat87** [comment]
Hey, sorry, I still see the header in the response. Can you give me an example curl request that can reproduce this problem? I'm not sure what I'm missing here.

![shot-2023-11-15-05-44-43](https://github.com/sharat87/httpbun/assets/120119/c6550950-d645-4d33-b2e4-f8227422135d)

**Comment by sharat87** [comment]
Hey @kuhnroyal, it looks like this is standard operating Golang/HTTP. Instead of the `Content-Length` header, we get a `Transfer-Encoding: chunked` when the body is over 2048 bytes. I do think it'd be more convenient if we just get the `Content-Length` header, but I'm trying to understand if you're working with a situation that doesn't understand the `Transfer-Encoding: chunked` header and is expecting the `Content-Length` at all times? Can you elaborate please? Thanks!

**Comment by kuhnroyal** [comment]
This makes sense. Just wondering how a client can figure out a total download size and progress.

**Comment by sharat87** [comment]
Hey, sorry, missed this notification. I think not knowing that is the point of using chunked encoding. In the sense that the server doesn't initially know how much data there's about to be. I don't understand it well enough yet so I'm not sure.

Either way, I think in our case here, adding the `Content-Type` might make things simpler. I'll pick this up soon.

**Comment by sharat87** [comment]
Fixed.

![shot-2023-12-02-03-43-11](https://github.com/sharat87/httpbun/assets/120119/c828bacd-dbaa-4915-9b59-1e088c0a8888)
